# SPDX-FileCopyrightText: 2023 KOINSLOT, Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Version, Publish, Release
on:
  push:
    branches:
    - main
jobs:

  version:
    uses: KOINSLOT-Inc/devkit/.github/workflows/version.reusable.yaml@main
    secrets: inherit
    permissions:
      contents: write

  upload_component:
    needs: version
    uses: KOINSLOT-Inc/devkit/.github/workflows/upload_component.reusable.yaml@main
    secrets: inherit

  release:
    needs: upload_component
    uses: KOINSLOT-Inc/devkit/.github/workflows/release.reusable.yaml@main
    secrets: inherit
    permissions:
      contents: write
